remove in-tree nav2 packages (use system default)

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -3,38 +3,26 @@ FROM ros:galactic
 ENV DEBIAN_FRONTEND=noninteractive
 
 RUN apt-get update
+RUN apt-get install -y ros-$ROS_DISTRO-filters libuvc-dev ros-$ROS_DISTRO-joint-state-publisher ros-$ROS_DISTRO-robot-localization ros-$ROS_DISTRO-rtabmap-ros ros-$ROS_DISTRO-depth-image-proc ros-$ROS_DISTRO-navigation2
 
 WORKDIR /work/ros2_ws
 
-RUN apt-get install -y ros-$ROS_DISTRO-filters
-RUN apt-get install -y libuvc-dev
-RUN apt-get install -y ros-$ROS_DISTRO-joint-state-publisher ros-$ROS_DISTRO-robot-localization ros-$ROS_DISTRO-rtabmap-ros
-
-# copy source code
 COPY wheeltec-ros2-src/src src
 
-# install dependencies
+# install dependencies, some may fail but practically it's ok
 RUN bash -c 'source /ros_entrypoint.sh && rosdep install --from-paths src -r -y || true'
 
-# LSM10
-# COPY LSM10 /tmp/LSM10
-# COPY LSM10/1-CMakeLists.txt src/wheeltec_lidar_ros2/LSlidar/lsm10_v2/CMakeLists.txt
-# RUN bash -c 'source /ros_entrypoint.sh && colcon build --symlink-install --packages-select lsm10_v2'
-# COPY LSM10/2-CMakeLists.txt src/wheeltec_lidar_ros2/LSlidar/lsm10_v2/CMakeLists.txt
-# RUN bash -c 'source /ros_entrypoint.sh && colcon build --symlink-install --packages-select lsm10_v2'
-
-ENV SKIP_PACKAGES="nav2_system_tests lsm10_v2"
+# some packages are not used, just skip them
+ENV SKIP_PACKAGES="lsm10_v2"
 # build!
+# '|| true's are needed because some packages may fail to build for the first time
 RUN bash -c 'source /ros_entrypoint.sh && colcon build --executor sequential --symlink-install --packages-skip $SKIP_PACKAGES' || true
 RUN bash -c 'source /ros_entrypoint.sh && colcon build --executor sequential --symlink-install --packages-select wheeltec_rrt_msg --packages-skip $SKIP_PACKAGES' || true
-ENV MAKEFLAGS="-j2"
 RUN bash -c 'source /ros_entrypoint.sh && source install/setup.bash && colcon build --executor sequential --symlink-install --packages-select wheeltec_robot_rrt --packages-skip SKIP_PACKAGES' || true
 RUN bash -c 'source /ros_entrypoint.sh && source install/setup.bash && colcon build --executor sequential --symlink-install --packages-skip $SKIP_PACKAGES'
-ENV MAKEFLAGS=
 ENV SKIP_PACKAGES=
 
-RUN apt-get install -y ros-$ROS_DISTRO-depth-image-proc
-
+# required for ros2_astra_camera
 ENV LD_LIBRARY_PATH="/work/ros2_ws/src/ros2_astra_camera-main/ros2_astra_camera/lib/openni2_redist/arm64:${LD_LIBRARY_PATH}"
 
 COPY camera_info /root/.ros/camera_info
